### ISSUE TITLE
Integration with Facebook React

### ISSUE THREAD

**Issue by mingfang** [kumailht/gridforms#25]
I'm trying to integrate Gridforms with  React.
The CSS part works but I can integration with the javascript part.
I'm not an expert but I think it's because gridforms.js currently initializes on startup but does not respond to DOM changes.

Do you have an recommendations?

**Comment by kumailht** [comment]
@mingfang I have very little experience with React so I'm not the best person to solve this. Maybe someone else reading this can help?

**Comment by atestu** [comment]
If you're using [newforms](https://github.com/insin/newforms), check this out: https://github.com/insin/newforms-gridforms
