### ISSUE TITLE
Print style?

### ISSUE THREAD

**Issue by mez** [kumailht/gridforms#30]
This is a very cool project. Would be super cool if one can directly print the forms! Just a suggestion.

**Comment by tslater** [comment]
+1

**Comment by nwmcsween** [comment]
++

**Comment by joshuapinter** [comment]
This has been added with #37.

Basically, it just works if you print from the browser but if you're using something like wkhtmltopdf to dynamically generate the PDFs, you'll need to ensure that the media type is set to 'print'. There's more details in the updated README now.
