### ISSUE TITLE
form not responding to show/hide

### ISSUE THREAD

**Issue by jd80104** [kumailht/gridforms#33]
I have a form with a textarea that is shown or hidden based on a response to a radio button.  When I open the textarea it overwrites part of the form.  Please let me know where to go to fix this issue.

BEFORE
![image](https://cloud.githubusercontent.com/assets/3800253/8173357/0a833972-1381-11e5-9044-430f9ec8aa19.png)

AFTER
![image](https://cloud.githubusercontent.com/assets/3800253/8173364/1d37f206-1381-11e5-8cdb-084d9e24705a.png)

**Comment by jd80104** [comment]
In further testing if I resize the browser window it come in line.  Do you have an event that can be called to refresh or do we need to write one?

**Comment by kumailht** [comment]
@jd80104 Have you tried calling ```that.equalizeFieldHeights();``` to refresh the form heights?

**Comment by jd80104** [comment]
Thank you for responding to my query.  I was able to solve it with $('window').resize but I will try your function.

**Comment by jd80104** [comment]
Thank you for your response.  Please be patient with me I have one more question.  I am getting an error on this line --> this.focusField(this.el.focusableFields.filter(':focus'));
 
SCRIPT438: Object doesn't support property or method 'focusField' 
gridforms.js, line 33 character 13
 Have you seen this before?  Any help?
 
Thank You!
 John D Sanders, CIO
 720.530.1030 (c)
 Email: john@seitmc.com
 Blog: http://seitmc.com/seitmcWP/
 LinkedIn: www.linkedin.com/in/johndsanders
 Twitter: @ITAdvisorJD
 Being recognized as valuable is never as gratifying as doing something valuable.
  
 
--------- Original Message --------- Subject: Re: [gridforms] form not responding to show/hide (#33)

**Comment by kumailht** [comment]
I have not come across this error before but I found this StackOverflow answer that might help:
http://stackoverflow.com/a/14003088
