### ISSUE TITLE
gridforms.sass fails to load with webpack/sass-loader

### ISSUE THREAD

**Issue by htaox** [kumailht/gridforms#43]
I am getting an error when using webpack/sass-loader to @import gridforms.sass: 

```Invalid CSS after "@mixin _reset": expected "{", was ";" (line 47, column 8)```

https://github.com/kumailht/gridforms/blob/master/gridforms/gridforms.sass#L47

When I do the following, the error goes away.  
(Should I @import other sass files as well?)

```
// =_reset
// or
=_reset {}
```

Thanks for this great lib, I :heart:  gridforms.

**Comment by nuschk** [comment]
Same here. I don't really understand where the _reset mixin is used anyway. It seems safe to drop it altogether.

**Comment by kumailht** [comment]
@htaox @nuschk That reset mixin definitely needs to go. Anyone up for making a quick pull request?

**Comment by nuschk** [comment]
Done, #57

**Comment by nuschk** [comment]
Figured it out, I hope. The build command is now in packages.json, so you can use `npm run build`, I hope that's ok for you.

**Comment by kumailht** [comment]
Perfect. I've merged the pull request. Thank you everyone for bringing this up and making the library better!
