### ISSUE TITLE
Field alignment (in a straight line) problem in a single row

### ISSUE THREAD

**Issue by ni8mr** [kumailht/gridforms#56]
Suppose we have a row with four different fields like this -

    <fieldset>
        <legend>Test form</legend>
        <div data-row-span="8">
            <div data-field-span="2">
                <input type="text">
            </div>
            <div data-field-span="2">
                <input type="text">    
            </div>
            <div data-field-span="2">
                <input type="checkbox">    
            </div>
            <div data-field-span="2">
                <select>
                   <option>1</option>
                   <option>2</option>
                </select>    
            </div>
         </div>
    </fieldset> 

When there are several rows (just like this row) one after another, alignment of the fields shattered. **Select** field takes more spaces than other fields.** Checkbox** field takes less spaces than other fields.  

I have tried to overcome this situation by applying custom CSS having **margin-bottom** or **margin-top** property. But it is a very tedious task and at the end for large amount of rows, it is almost impossible.

It would be a best solution, if someone add a built-in feature to handle such cases.

**Comment by kumailht** [comment]
I implemented the markup you posted in the example file (`kumailht.com/gridforms/example.html`) and it seems to work fine. Screenshot below:
<img width="1026" alt="screen shot 2016-07-13 at 3 02 39 pm" src="https://cloud.githubusercontent.com/assets/763012/16801285/df518518-490a-11e6-9fb5-923fd8b6a7b1.png">

Not sure if this is a bug in GridForms or your implementation. Please reopen this issue with a screenshot and browser information if the bug persists.

PS: Apologies for the outrageously long response time.
