### ISSUE TITLE
Hover CSS is taking precedence over focus

### ISSUE THREAD

**Issue by solsticesurfer** [kumailht/gridforms#58]
The hover effect is taking precedence over the focus event on grid-form fields. The result is that a field will not use its focus color until the mouse is moved away from the field that has focus. The expected behavior would be to highlight the field when clicked on.

The fix is very easy: in gridforms.css, simply swap the CSS declarations for focus and hover, lines 21-23 from
```
21: .grid-form [data-row-span] [data-field-span].focus { background: #fffad4; }
22: .grid-form [data-row-span] [data-field-span].focus label { color: #262626; }
23: .grid-form [data-row-span] [data-field-span]:hover { background: #fffded; cursor: text; }
```
to

```
21: .grid-form [data-row-span] [data-field-span]:hover { background: #fffded; cursor: text; }
22: .grid-form [data-row-span] [data-field-span].focus { background: #fffad4; }
23: .grid-form [data-row-span] [data-field-span].focus label { color: #262626; }
```

**Comment by kumailht** [comment]
Nice bug spotting skills there! Would you like to contribute a pull request with the changes?

**Comment by solsticesurfer** [comment]
Happy to give it a go. This is my first attempt at a pull request. Please let me know if I got it right.

**Comment by kumailht** [comment]
Merged: https://github.com/kumailht/gridforms/pull/59
