### ISSUE TITLE
increase text input field target size to cover entire grid cell for clicks/taps

### ISSUE THREAD

**Issue by kimslawson** [kumailht/gridforms#62]
Currently there looks to be an affordance to click within the grid anywhere in a cell to input text. There is however a dead zone around the text input field that does not accept clicks or taps. Much as html link padding can be increased to cover adjacent space, we can do the same with input fields by first adding padding, then subtracting an equal amount of margin. This allows the user to click anywhere in the grid cell to focus the input.

Consider increasing target for accepting clicks/taps to focus text inputs as quickly demonstrated in the attachment (red just for visual demo of increased email field target size compared to blue background showing size of location field).

<img width="1242" alt="screen shot 2016-12-11 at 20 06 41" src="https://cloud.githubusercontent.com/assets/249884/21085239/752e26ba-bfdd-11e6-9817-37336abc432c.png">

**Comment by kumailht** [comment]
The target area should be the entire field. Perhaps the Javascript is failing to load?
